RUN_ID=private_mlp_test MLP_WINDOW=1536 MLP_OVERLAP=0.7 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=32 ADAPT_RANK=0 PRIVATE_MLP_RANK=16 NUM_LAYERS=11 ATTEND_EVERY=1 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

VAL_LOSS_EVERY=200 MLP_WIDTH=3072 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=32 ADAPT_RANK=0 PRIVATE_MLP_RANK=16 NUM_LAYERS=11 ATTEND_EVERY=1 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py
# Increase size to try beat training velocity
VAL_LOSS_EVERY=200 MLP_WIDTH=4096 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=64 ADAPT_RANK=0 PRIVATE_MLP_RANK=16 NUM_LAYERS=12 ATTEND_EVERY=1 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

VAL_LOSS_EVERY=200 MLP_WIDTH=6144 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=48 ADAPT_RANK=0 PRIVATE_MLP_RANK=32 NUM_LAYERS=11 ATTEND_EVERY=1 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py


VAL_LOSS_EVERY=200 MLP_WIDTH=2048 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=32 ADAPT_RANK=0 PRIVATE_MLP_RANK=32 NUM_LAYERS=11 ATTEND_EVERY=1 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

MLP_WIDTH=6144 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=48 ADAPT_RANK=0 PRIVATE_MLP_RANK=32 NUM_LAYERS=12 ATTEND_EVERY=1 VAL_LOSS_EVERY=200 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

MLP_WIDTH=2048 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=128 ADAPT_RANK=0 PRIVATE_MLP_RANK=32 NUM_LAYERS=12 ATTEND_EVERY=1 VAL_LOSS_EVERY=200 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

MLP_WIDTH=4096 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=128 GATE_RANK=64 ADAPT_RANK=0 PRIVATE_MLP_RANK=32 NUM_LAYERS=12 ATTEND_EVERY=1 VAL_LOSS_EVERY=200 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

#Best
MLP_WIDTH=4096 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=128 ADAPT_RANK=0 PRIVATE_MLP_RANK=32 NUM_LAYERS=12 ATTEND_EVERY=1 VAL_LOSS_EVERY=200 torchrun --standalone --nproc_per_node=8 train_gpt_ours.py
# Staged learning test run
RUN_ID=staged_learning MLP_WIDTH=4096 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=128 ADAPT_RANK=0 PRIVATE_MLP_RANK=32 NUM_LAYERS=12 ATTEND_EVERY=1 VAL_LOSS_EVERY=200 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

# early warmdown 1 gpu
RUN_ID=early_warmdown EMA_SHARED_BETA=0.995 MLP_WIDTH=3328 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=32 ADAPT_RANK=16 PRIVATE_MLP_RANK=0 NUM_LAYERS=12 ATTEND_EVERY=1 VAL_LOSS_EVERY=200 WARMDOWN_ITERS=300 torchrun --standalone --nproc_per_node=1 train_gpt_ours.py

# early warmdown 8 gpu
RUN_ID=moe_mlp MLP_WIDTH=4096 NUM_BANKS=8 ACTIVE_BANKS=2 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=0 ADAPT_RANK=0 PRIVATE_MLP_RANK=0 NUM_LAYERS=12 ATTEND_EVERY=1 VAL_LOSS_EVERY=200 WARMDOWN_ITERS=3000 torchrun --standalone --nproc_per_node=8 train_gpt_ours.py

# early warmdown 8 gpu
RUN_ID=moe_mlp_super_sparse MLP_WIDTH=8192 NUM_BANKS=16 ACTIVE_BANKS=3 MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 GATE_RANK=0 ADAPT_RANK=0 PRIVATE_MLP_RANK=0 NUM_LAYERS=8 ATTEND_EVERY=2 VAL_LOSS_EVERY=200 WARMDOWN_ITERS=6000 torchrun --standalone --nproc_per_node=8 train_gpt_ours.py

RUN_ID=balanced \
MLP_WIDTH=8192 NUM_BANKS=16 ACTIVE_BANKS=2 \
MTP_HEADS=0 Q_LATENT=0 KV_LATENT=64 \
GATE_RANK=0 PRIVATE_MLP_RANK=0 \
NUM_LAYERS=11 ATTEND_EVERY=1 ADAPT_RANK=16 \
VAL_LOSS_EVERY=200 WARMDOWN_ITERS=3000 \
torchrun --standalone --nproc_per_node=8 train_gpt_ours.py

RUN_ID=balanced_no_mla \
MLP_WIDTH=8192 NUM_BANKS=16 ACTIVE_BANKS=2 \
MTP_HEADS=0 Q_LATENT=0 KV_LATENT=0 \
GATE_RANK=0 PRIVATE_MLP_RANK=0 \
NUM_LAYERS=11 ATTEND_EVERY=1 ADAPT_RANK=16 \
VAL_LOSS_EVERY=200 WARMDOWN_ITERS=3000 \
torchrun --standalone --nproc_per_node=8 train_gpt_ours.py

RUN_ID=small_banks \
MLP_WIDTH=4096 NUM_BANKS=4 ACTIVE_BANKS=2 \
MTP_HEADS=0 Q_LATENT=0 KV_LATENT=0 \
GATE_RANK=0 ADAPT_RANK=0 PRIVATE_MLP_RANK=0 \
NUM_LAYERS=11 ATTEND_EVERY=1 ADAPT_RANK=16 \
VAL_LOSS_EVERY=200 WARMDOWN_ITERS=3000 \
torchrun --standalone --nproc_per_node=8 train_gpt_ours.py

# V2
RUN_ID=latent_larger NUM_LAYERS=12  VAL_LOSS_EVERY=200 KV_LATENT=64 torchrun --standalone --nproc_per_node=8 train_gpt_v2.py


